// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp2H-wqVIhA3QvOMiavui9TDy4MAaI8zE',
    appId: '1:732543311140:web:65e0b19a89a0c12fe627b1',
    messagingSenderId: '732543311140',
    projectId: 'flutter-firebase-project-b39c6',
    authDomain: 'flutter-firebase-project-b39c6.firebaseapp.com',
    storageBucket: 'flutter-firebase-project-b39c6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaqdaViqqggkZo1W1_E7QGQgU-ZGTz6QE',
    appId: '1:732543311140:android:d9b426435d078aa4e627b1',
    messagingSenderId: '732543311140',
    projectId: 'flutter-firebase-project-b39c6',
    storageBucket: 'flutter-firebase-project-b39c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc-EQVcH018A6DI-Fx00EDMbf3K8o6GfY',
    appId: '1:732543311140:ios:153c09c48efd9d72e627b1',
    messagingSenderId: '732543311140',
    projectId: 'flutter-firebase-project-b39c6',
    storageBucket: 'flutter-firebase-project-b39c6.appspot.com',
    iosBundleId: 'com.example.proyectoPrograMovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc-EQVcH018A6DI-Fx00EDMbf3K8o6GfY',
    appId: '1:732543311140:ios:153c09c48efd9d72e627b1',
    messagingSenderId: '732543311140',
    projectId: 'flutter-firebase-project-b39c6',
    storageBucket: 'flutter-firebase-project-b39c6.appspot.com',
    iosBundleId: 'com.example.proyectoPrograMovil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp2H-wqVIhA3QvOMiavui9TDy4MAaI8zE',
    appId: '1:732543311140:web:16cd658e4b541cc5e627b1',
    messagingSenderId: '732543311140',
    projectId: 'flutter-firebase-project-b39c6',
    authDomain: 'flutter-firebase-project-b39c6.firebaseapp.com',
    storageBucket: 'flutter-firebase-project-b39c6.appspot.com',
  );
}
